### ISSUE TITLE
Unable to create PR on Authn repo

### ISSUE THREAD

**Issue by ahtesham-quraish** [openedx/axim-engineering#1014]
### Firm Name

Vangurds Authn team

### Urgency

Medium (< 2 weeks)

### Requested Change

I am trying to create PR on this Repo
<https://github.com/openedx/frontend-app-authn> but don't see the 'Create
Pull Request' button. Can you please check what the issue is? This is
likely that someone has changed my permissions.

My github username is *ahtesham-quraish*.

### Reasoning

I have to create PR for my code changes in vanguards team.

**Comment by feanil** [comment]
I took a look at the permissions on the repo and you should have write access via two different teams: 
![image](https://github.com/openedx/axim-engineering/assets/781561/0cff384d-ab87-4e94-8634-cbafa15de282)
Can you provide the URL and screenshots of the page where you're seeing the issue?

**Comment by kdmccormick** [comment]
Hey @ahtesham-quraish , permissions would not affect your ability to create a PR. Even GitHub users without any write access are allowed to create PRs. If the "Create PR" button is not showing up on the repo's homepage (because you have not pushed a branch recently), it should be visible as "New Pull Request" in the top-right corner of the [pull requests page](https://github.com/openedx/frontend-app-authn/pulls):
![image](https://github.com/openedx/axim-engineering/assets/3628148/0287a943-436a-49e2-99c0-a095f936e5c7). Make sure you are logged in.

If you aren't seeing a button there, I recommend contacting GitHub support.
