### ISSUE TITLE
Backstage - how to indicate an empty owner?

### ISSUE THREAD

**Issue by jristau1984** [openedx/axim-engineering#1102]
### Repository

axim-engineering

### Urgency

Low (2 weeks)

### Requested Change

I do not know the right syntax to use in catalog-info.yaml files to get Backstage to understand an empty owner field.  I have tried a blank, single quotes, and ~.  The old entry still persists in Backstage, and I have seen other updates take effect there.  

### Reasoning

I am trying to get Backstage to match new ownership.

**Comment by jristau1984** [comment]
Example https://github.com/openedx/django-config-models/blob/master/catalog-info.yaml

**Comment by sarina** [comment]
This is a good question that I don't know the answer to. @feanil could you assist?

**Comment by feanil** [comment]
Since the field is required, it needs to be a valid value, and it looks like the fallback when an update is not valid is to not make the update.  To resolve this, I've created the `openedx-unmaintained` team which can be assigned as the owner for any repos you want to give up maintainership on @jristau1984.
