### ISSUE TITLE
[GH Request] Short-term codecov fix

### ISSUE THREAD

**Issue by kdmccormick** [openedx/axim-engineering#1164]
### Firm Name

Maintenance WG

### Urgency

Medium (< 2 weeks)

### Requested Change

?

### Reasoning

?

**Comment by arbrandes** [comment]
It seems global upload token generation is finally working for our org... and so is the token itself:

https://github.com/openedx/frontend-template-application/pull/798

**Comment by arbrandes** [comment]
I've gone ahead and issued PRs that update codecov-action for the frontend repos because their workflows are more standardized and thus passive to a couple of grep/sed loops.

https://github.com/openedx/wg-frontend/issues/179

I've also updated the [Adding Codecov](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3438280709/Adding+Codecov) wiki page with a comment to the effect that we can now use an org-wide token.

Otherwise, I'm calling this closed as far as on-call goes.
