### ISSUE TITLE
Arbi-BOM team is slowed down by lack of push-pull-all access

### ISSUE THREAD

**Issue by jristau1984** [openedx/axim-engineering#1261]
### Firm Name

2U

### Urgency

Medium (< 2 weeks)

### Requested Change

Axim to discuss, propose, and implement a solution to the problem stated in the Reasoning field.

### Reasoning

2U Arbi-BOM team has new members that have joined as well as senior team members who want to take extended leave.  Currently, the new hire is on-call and cannot merge upgrade/maintenance PRs to repos.  How can the team have the access they need to continue to effectively and efficiently maintain many repos across the project?

**Comment by feanil** [comment]
@jristau1984 longer term, I think it makes sense to introduce a new type of CC role, that would get broad access but with a narrow mission of simply doing upgrades and maintenance across a group of repos.  The expectation would be that the whole group could have this access and new people who are joining the team could do work without it until they can be nominated for this role.

Shorter term since the role and related process don't exist yet, is there anything specific access changes you need right now?

**Comment by jristau1984** [comment]
Thanks, @feanil .  The short term actions we are requesting include:

1. Add Hunia Fatima (huniafatima-arbi) to the Arbi-BOM team
2. Add Bilal Qamar (BilalQamar95) to the Arbi-BOM team
3. Add the Arbi-BOM team to the Arch-BOM team

**Comment by feanil** [comment]
Hey Jeremy, they've been added to the Arbi-BOM team but currently we're not adding teams to other teams because it adds some maintenance complexity.
