### ISSUE TITLE
Figure out a way to apply theme changes without requiring a full container rebuild

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/axim-engineering#420]
### Problem

Theme changes occur often enough and for enough instances that for many Open edX providers, this can become cost-prohibitive in terms of CPU time.  (In one specific case: “1000 hours of compute time in an m5.large machine for building all of them”). 

### Product/Platform Value

This furthers adoption, as it reduces the friction for providers that require custom theming, by reducing the need to rebuild images.  And in addition to reducing the number of builds, this has the potential to reduce build time. It would also remove the blocker for multi-tenancy sites to upgrade beyond Koa. 

### Acceptance Criteria

A theming system where artifacts were built, and possibly hosted, separately would solve the problem.

### Related or in-progress work

OpenCraft has begun preliminary work via these two co-dependent ADRs:

* https://github.com/openedx/paragon/pull/1388
* https://github.com/openedx/frontend-platform/pull/351

### Contingencies

https://github.com/openedx/tcril-engineering/issues/418

**Comment by arbrandes** [comment]
The solution is likely to come about as a part of https://github.com/openedx/open-edx-proposals/pull/410.

**Comment by arbrandes** [comment]
This is _actually_ going to come about as a feature of [Paragon Design Tokens](https://github.com/openedx/paragon/blob/3e83359c2ff63ee77fedb091fe00ef13dc07123f/docs/decisions/0019-scaling-styles-with-design-tokens.rst#L4), which will let people pull in stylesheets on demand at runtime.  Since that's already in progress, I think we can close this.
