### ISSUE TITLE
[GH Request] Onboard Gideon Gitau

### ISSUE THREAD

**Issue by mmnxumalo** [openedx/axim-engineering#809]
### Firm Name

EdX

### User List (case sensitive!) - Please also include in ticket title

Gideon Gitau

### Start Date

28 June 2023

### Urgency

High (< 3 days)

### Special Requests

https://github.com/openedx/configuration

**Comment by bmtcril** [comment]
HI @mmnxumalo , we (Axim) are blocked on being able to onboard users for you since we don't know that you are someone who can approve these requests. We usually rely on @georgebabey to confirm this for us, but he hasn't responded in your [last ticket](https://github.com/openedx/axim-engineering/issues/792) or a few others that are waiting. There are several people in 2U IT that are known to us and can make this request for you if you are blocked. I will also reach out and see if there is someone besides George that can help us move these requests forward.

**Comment by georgebabey** [comment]
Sorry for the slow reply here - this is approved and @mmnxumalo is from our IT dept.

**Comment by bmtcril** [comment]
@mmnxumalo can we get your first and last name, as well as email address so we can add you to our list of folks who can request this access?

**Comment by bmtcril** [comment]
@mmnxumalo we also need Gideon's email address and github username.

**Comment by mmnxumalo** [comment]
@bmtcril 
Name: Gideon Gitau	
Email: ggitau@2u.com
Username: giddygitau

**Comment by bmtcril** [comment]
@mmnxumalo Gideon has been invited to the org, but we won't be able to add him to the configuration repo and close the ticket out until he accepts.

**Comment by bmtcril** [comment]
Ah nevermind, that repo is in push-pull-all, so he already has access. This should be all set.

**Comment by bmtcril** [comment]
They have not accepted the invitation.

**Comment by mmnxumalo** [comment]
@bmtcril invite received and accepted, so all good. thanks
