### ISSUE TITLE
[GH Request] Allow edx-transifex-bot to merge to edx-platform without review

### ISSUE THREAD

**Issue by rgraber** [openedx/axim-engineering#940]
### Firm Name

2U

### Urgency

Low (2 weeks)

### Requested Change

We would like the edx-transifex-bot to be able to merge its own PRs into edx-platform without review. 

### Reasoning

There is a Jenkins job in 2U that creates these PRs. It used to merge them automatically but since the recent change to edx-platform permissions, the job has started failing because the PRs aren't merged. It seems like unnecessary toil to have 2U or Axim employees go in and manually merge translations PRs when they happen.

**Comment by kdmccormick** [comment]
We'd like this too, but we're trying to find a way of doing it with giving blanket admin rights back to the bot.

I've just granted the bot an exception to the PR rule:
![image](https://github.com/openedx/axim-engineering/assets/3628148/29122607-9985-4b22-b121-592515e1c164)

It's a little counterintuitive, but I think this might allow it to merge PRs without approval. Could you re-run the job and see if it works?

If it works, we can apply to this uniformly to all repos.

By the way, I'm looking into a similar issue for [credentials repos](https://github.com/openedx/axim-engineering/issues/909), but it seems like there's also a secondary issue going on there, and I'm still waiting for logs in order to diagnose it.

**Comment by rgraber** [comment]
Ugh, the job is failing for unrelated reasons. Might take a bit.

**Comment by rgraber** [comment]
No dice https://github.com/openedx/edx-platform/pull/33526

**Comment by kdmccormick** [comment]
Ah, bummer. I've made the bot an admin on edx-platform, can you try again @rgraber ?

**Comment by kdmccormick** [comment]
@rgraber I just realized I didn't hit "Save" when I tried this: https://github.com/openedx/axim-engineering/issues/940#issuecomment-1766723462 🤦🏻 

I've revoked admin permission from the bot again, but I've actually modified the branch protection rule this time. Try now, and if it still doesn't work, then I'll definitely give the bot access again.

**Comment by rgraber** [comment]
No dice, it's still stuck on review

**Comment by rgraber** [comment]
Is this just a permissions issue or do we also need logic that says "automerge these PRs?"

**Comment by kdmccormick** [comment]
OK, the branch protection exemption definitely doesn't work like I'd hoped then.

I've made the bot an admin again, can you try one last time?

![image](https://github.com/openedx/axim-engineering/assets/3628148/1a8e0da6-9fa5-4eb2-a84f-5785113b1048)

> Is this just a permissions issue or do we also need to put back additional logic that says "automerge these PRs?"

This will be the first time we're trying with the bot having its full admin rights back on edx-platform. So I think this will do it, but if it doesn't, then maybe there's additional logic we need to figure out.

**Comment by rgraber** [comment]
Now I'm getting ``'Commit' object has no attribute 'get_check_runs'`` which doesn't make sense to me, but seems to be consistent and only happened after the bot was made an admin so is seemingly related. Looking more.

**Comment by rgraber** [comment]
I wonder if it's an API key thing, where the key doesn't have permission to get the commit and so it comes back null or something. It's a terrible design choice but it wouldn't surprise me.

**Comment by kdmccormick** [comment]
Ack. There's a couple more permutations we can try on this side:

1. Demote the bot from admin->write, but also turn the PR-requires-approving-review setting back off, which I think kicked off this whole problem
2. Promote back to from write->admin, if (1) doesn't work

I'm hoping one of those works so we don't have to dive deeper into debugging this deprecated job 😛 

I just did (1), can you try again?

**Comment by rgraber** [comment]
That seems to have worked, although I did manually rerun some of the unit tests when they failed on connection blips. I think we can close this for now, and reopen if it fails again.

**Comment by kdmccormick** [comment]
Phew, thanks for your help.

**Comment by deborahgu** [comment]
Reporting something on this closed issue that I believe is an instance of the same problem: [LRMFE PR #218](https://github.com/openedx/frontend-app-learner-record/pull/218) passes all of its checks but fails to merge in Jenkins, 

I'm not reopening this  ticket  myself because I'm not sure, but @kdmccormick, i wanted to flag for your attention.

**Comment by kdmccormick** [comment]
Thanks @deborahgu , looks like the same exact problem. I'll take a look.

**Comment by sarina** [comment]
@kdmccormick is this issue still unresolved?

**Comment by feanil** [comment]
@kdmccormick checking back in on this, can this be closed or is there still more work to be done?

**Comment by kdmccormick** [comment]
I'm sorry, I don't know, and I can't do any work on it this week.

**Comment by feanil** [comment]
@rgraber do you know if this is still an issue?

**Comment by feanil** [comment]
Actually, looking at the PR history on edx-platform I see that there was an auto merge of translations last week and it's been fine for a while so I'm gonna close this ticket.
