### ISSUE TITLE
[GH Request] Make Repo

### ISSUE THREAD

**Issue by hajorg** [openedx/axim-engineering#947]
### Firm Name

2U

### Urgency

Medium (< 2 weeks)

### Problem/Request

Requesting a new repository

### Reasoning

New repository
Name: frontend-component-ai-translations
Maintainer: @jristau1984
Default branch name: main
Protected Branch: main

**Comment by bmtcril** [comment]
I have created a bare repository with only the following settings:

- `main` is the main branch, and protected (require PR, require approvals, require status checks to pass even though there are no status checks yet)
- Issues on, wiki off, discussions off, projects off
- AGPL-3.0 license
- Bare readme
- committers-frontend-component-ai-translations team created with write access and membership granted to @jristau1984 

Jeremy is on the hook for setting things up to maintainership standards, because of the review permissions I'm probably the only person who can approve things to get started. If there are other folks who should be added to the team to lessen that burden let me know. Same for any additional settings changes that may come up.

**Comment by jristau1984** [comment]
Is it possible to make me the admin of that team, so I can add team members
myself?

Thanks,
Jeremy Ristau
Engineering Director - edX/2U

**Comment by bmtcril** [comment]
Sorry, that's not a level of access we give out
